on:
  workflow_dispatch:

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "The job is running"
        if: ${{ github.event_name == 'push' || github.ref == 'refs/head/main' || !contains(github.event.head_commit_message, 'WIP') || startsWith(github.ref, 'refs/tags/v') }} # WIP => work in progress
      - name: Clean Up on failure
        run: echo "Deployment Succeeded"
        if: success()
        # always() -> always runs regardless of the previous step result
        # cancelled() -> if the previous step was cancelled
